/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.MySQL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CleaningArticle;

/**
 *
 * @author Usuario
 */
public class VtnEmpleado extends javax.swing.JFrame {

    private int employeeCode;
    CleaningArticle ca = new CleaningArticle();
    MySQL bd = new MySQL("articulos", "root", "");
    DefaultTableModel model;
    
    /**
     * Creates new form VtnEmpleado
     */
    public VtnEmpleado() {
        initComponents();
        String[] titulos = {"Código", "Nombre", "Estatus"};
        model = new DefaultTableModel(null, titulos);
        tblBusqueda.setModel(model);
        this.showInTable();
        this.setLocationRelativeTo(null);
    }

    public VtnEmpleado(int employeeCode) {
        initComponents();
        String[] titulos = {"Código", "Nombre", "Estatus"};
        model = new DefaultTableModel(null, titulos);
        tblBusqueda.setModel(model);
        this.showInTable();
        this.setLocationRelativeTo(null);
        this.employeeCode = employeeCode;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblEmpleado = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBusqueda = new javax.swing.JTable();
        txtCodigo = new javax.swing.JTextField();
        btnPedir = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLEADO");

        jPanel1.setBackground(new java.awt.Color(240, 205, 252));

        lblEmpleado.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        lblEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmpleado.setText("EMPLEADO");

        lblInventario.setFont(new java.awt.Font("Malgun Gothic", 1, 14)); // NOI18N
        lblInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventario.setText("Inventario");

        tblBusqueda.setBackground(new java.awt.Color(255, 153, 255));
        tblBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        tblBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Estatus"
            }
        ));
        tblBusqueda.setEnabled(false);
        tblBusqueda.setSelectionBackground(new java.awt.Color(240, 179, 242));
        jScrollPane1.setViewportView(tblBusqueda);

        txtCodigo.setBackground(new java.awt.Color(255, 211, 244));

        btnPedir.setBackground(new java.awt.Color(240, 179, 242));
        btnPedir.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnPedir.setText("Pedir");
        btnPedir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPedir.setBorderPainted(false);
        btnPedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedirActionPerformed(evt);
            }
        });

        btnDevolver.setBackground(new java.awt.Color(240, 179, 242));
        btnDevolver.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDevolver.setBorderPainted(false);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(240, 179, 242));
        btnRegresar.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnPedir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(btnRegresar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInventario)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPedir)
                    .addComponent(btnDevolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        VtnPrincipal main = new VtnPrincipal();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedirActionPerformed
        ca = bd.searchInTable(txtCodigo.getText());
        if (ca != null) {
            if (!ca.getStatus()) {
                ca.updateArticleStatus(txtCodigo.getText(), 1);
            } else {
                JOptionPane.showMessageDialog(this, "El articulo que busca no se encuentra disponible");
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el articulo");
        }
        this.showInTable();
    }//GEN-LAST:event_btnPedirActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        ca = bd.searchInTable(txtCodigo.getText());
        if (ca != null) {
            if (ca.getStatus()) {
                ca.updateArticleStatus(txtCodigo.getText(), 0);
            } else {
                JOptionPane.showMessageDialog(this, "El articulo ya se encuentra en el almacen");
            }

        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el articulo");
        }
        this.showInTable();
    }//GEN-LAST:event_btnDevolverActionPerformed

    public void showInTable() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        String lended;

        MySQL bd = new MySQL("articulos", "root", "");
        try {
            PreparedStatement query = bd.CreateSelectStatement("cleaning_article");
            ResultSet cleaningArticles = bd.Select(query);
            while (cleaningArticles.next()) {
                if (cleaningArticles.getInt("lended") == 1) {
                    lended = "Prestado";
                } else {
                    lended = "Disponible";
                }

                Object[] oUsuario = {cleaningArticles.getString("code"),
                    cleaningArticles.getString("name"),
                    lended};
                model.addRow(oUsuario);
            }
            bd.CloseConnection();
        } catch (Exception err) {
            bd.HandleError("Error al consultar usuario", err);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnPedir;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JTable tblBusqueda;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
